### ISSUE TITLE
Adapt `MainMethodChecker` for instance main methods (JEP 445, 463, 477) 

### ISSUE THREAD

**Issue by b-fein** [uni-passau-artemis/pipeline-helper#3]
Future Java releases might allow the declaration of the `main` method as instance method of a class. It might also allow multiple `main` methods and have a specific order in which they are used.
The current implementation of the `MainMethodChecker` does not consider those new alternatives to the currently only allowed versions `public static void main(String[] args)` or `public static void main(String... args)`.

- Relevant details in the JEP: https://openjdk.org/jeps/463
- Third preview: https://openjdk.org/jeps/8323335, https://bugs.openjdk.org/browse/JDK-8323335

**Comment by chbachm** [comment]
Java 22 Preview 2 does not use "inherited" static main method as candidate for the start point any more.

```java
public class SMain {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }

//    public void main() {
//        System.out.println("Hello, World!");
//    }
}


public class Main extends SMain {
   // ok in Java 21/22 without preview, with preview on no main Method found error although in name space
   // with dynamic SMain.main() not commented out ok with preview on
}


import java.lang.reflect.Method;

public class Main extends SMain {
    public void main() throws Exception {	// warning on program start SMain.main(String[]) not used
        System.out.println("subsubsub");
        Main.main(new String[] {});             // in namespace

        Class<Main> c = Main.class;
        Method m = c.getMethod("main", String[].class);
        System.out.print(m);
        if (!c.equals(m.getDeclaringClass())) {
            System.out.println("\tno candidate");
        }
        m = c.getMethod("main", String[].class);
        m = c.getMethod("main");
        System.out.print(m);
    }
}
```

**Comment by BaumiCoder** [comment]
Actual JEPS for this issue: https://openjdk.org/jeps/477

**Comment by chbachm** [comment]
In https://github.com/uni-passau-artemis/pipeline-helper/issues/3#issuecomment-1820483096 I wrote:
> Java 22 Preview 2 does not use "inherited" static main method as candidate for the start point any more.

Java 23 release does allow "inherited" static main method as atart point again (with --enable-preview), which seems a quite natural cosequence, as it is in the namespace of the subclass.
